# Generated by Django 4.2.1 on 2023-07-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.TimeField()),
                ('fullCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patientCopayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hiCopayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[(1, 'Pendiente'), (2, 'Confirmado'), (3, 'Cancelado'), (4, 'Pagado'), (5, 'Adeuda')], max_length=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersProfile.doctorprofile')),
                ('healthInsurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersProfile.healthinsurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersProfile.patientprofile')),
            ],
        ),
    ]
