# Generated by Django 4.2.1 on 2023-07-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='fullCost',
            new_name='full_cost',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='healthInsurance',
            new_name='health_insurance',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='hiCopayment',
            new_name='hi_copayment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patientCopayment',
            new_name='patient_copayment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Confirmado'), ('3', 'Cancelado'), ('4', 'Pagado'), ('5', 'Adeuda')], max_length=1),
        ),
    ]
