# Generated by Django 4.2.1 on 2023-07-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_fullcost_appointment_full_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hi_copayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_copayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
