# Generated by Django 4.2.1 on 2023-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Confirmado'), ('3', 'Adeuda'), ('4', 'Pagado')], max_length=1),
        ),
    ]
