# Generated by Django 4.2.1 on 2023-08-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0007_rename_appoimentduration_doctorprofile_appointment_duration'),
        ('appointments', '0008_alter_appointment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersProfile.medicalspeciality'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersProfile.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='health_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersProfile.healthinsurance'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersProfile.patientprofile'),
        ),
    ]
