# Generated by Django 4.2.1 on 2023-09-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmado'), (3, 'Adeuda'), (4, 'Pagado')], default=1),
        ),
    ]
