# Generated by Django 4.2.1 on 2024-01-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='state',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CONFIRMADO')], default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'ADEUDA'), (2, 'PAGADO')], default=1),
        ),
    ]
