# Generated by Django 4.2.1 on 2024-01-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_remove_appointment_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'CONFIRMADO'), (3, 'FINALIZADO')], default=1),
        ),
    ]
