# Generated by Django 4.2.1 on 2024-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.IntegerField(choices=[(1, 'PRESENCIAL'), (2, 'VIRTUAL')], default=1),
        ),
    ]
