# Generated by Django 4.2.1 on 2023-08-29 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_state'),
        ('usersProfile', '0009_insuranceplanseminarist_seminaristprofile_and_more'),
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingNumber', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'En Espera'), (2, 'Confirmado')], default=1)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersProfile.healthinsurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersProfile.patientprofile')),
                ('paymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarRoomUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encountersCount', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.room')),
            ],
        ),
        migrations.AddField(
            model_name='seminar',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='maxInscription',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='seminar',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='month',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_index=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.AddField(
            model_name='seminarroomusage',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.seminar'),
        ),
        migrations.AddField(
            model_name='seminarinscription',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.seminar'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='patients',
            field=models.ManyToManyField(related_name='seminaries', through='seminar.SeminarInscription', to='usersProfile.patientprofile'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='rooms',
            field=models.ManyToManyField(through='seminar.SeminarRoomUsage', to='seminar.room'),
        ),
    ]
