# Generated by Django 4.2.1 on 2023-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_alter_seminar_month_alter_seminar_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='weekday',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=12),
        ),
    ]
