# Generated by Django 4.2.1 on 2024-01-24 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_appointment_appointment_status'),
        ('seminar', '0007_alter_seminar_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=12)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='weekday',
        ),
        migrations.RemoveField(
            model_name='seminarinscription',
            name='payment',
        ),
        migrations.AddField(
            model_name='seminarinscription',
            name='hi_copayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='seminarinscription',
            name='patient_copayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='seminarinscription',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='year',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2060)]),
        ),
        migrations.AddField(
            model_name='seminar',
            name='schedule',
            field=models.ManyToManyField(to='seminar.seminarschedule'),
        ),
    ]
