# Generated by Django 4.2.1 on 2024-01-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0008_seminarschedule_remove_seminar_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminarinscription',
            old_name='state',
            new_name='seminar_status',
        ),
        migrations.AddField(
            model_name='seminarinscription',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'ADEUDA'), (2, 'PAGADO')], default=1),
        ),
    ]
