# Generated by Django 4.2.1 on 2024-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0009_rename_state_seminarinscription_seminar_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarschedule',
            name='weekday',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12),
        ),
    ]
