# Generated by Django 4.2.1 on 2024-01-31 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0013_specialitybranch_is_active'),
        ('seminar', '0009_rename_state_seminarinscription_seminar_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarinscription',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersProfile.healthinsurance'),
        ),
        migrations.AlterField(
            model_name='seminarschedule',
            name='weekday',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12),
        ),
    ]
