# Generated by Django 4.2.1 on 2024-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0010_alter_seminarinscription_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarinscription',
            name='seminar_status',
            field=models.IntegerField(choices=[(1, 'EN ESPERA'), (2, 'CONFIRMADO'), (3, 'BAJA SOLICITADA'), (4, 'BAJA CONFIRMADA')], default=1),
        ),
    ]
