# Generated by Django 4.2.1 on 2024-02-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0010_alter_seminarschedule_weekday'),
        ('seminar', '0011_alter_seminarinscription_seminar_status'),
    ]

    operations = [
    ]
