# Generated by Django 4.2.1 on 2023-08-07 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0004_alter_healthinsurance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='appoimentDuration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
    ]
