# Generated by Django 4.2.1 on 2023-08-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0006_alter_doctorprofile_appoimentduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='appoimentDuration',
            new_name='appointment_duration',
        ),
    ]
