# Generated by Django 4.2.1 on 2023-08-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0007_specialitybranch_insuranceplandoctor_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insuranceplandoctor',
            unique_together={('doctor', 'insurance', 'branch')},
        ),
    ]
