# Generated by Django 4.2.1 on 2023-08-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0007_rename_appoimentduration_doctorprofile_appointment_duration'),
        ('usersProfile', '0008_alter_insuranceplandoctor_unique_together'),
    ]

    operations = [
    ]
