# Generated by Django 4.2.1 on 2023-08-24 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersProfile', '0008_alter_insuranceplandoctor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlanSeminarist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersProfile.healthinsurance')),
            ],
        ),
        migrations.CreateModel(
            name='SeminaristProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('insurances', models.ManyToManyField(through='usersProfile.InsurancePlanSeminarist', to='usersProfile.healthinsurance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seminaristProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tallerista',
                'verbose_name_plural': 'Talleristas',
            },
        ),
        migrations.AddField(
            model_name='insuranceplanseminarist',
            name='seminarist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersProfile.seminaristprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='insuranceplanseminarist',
            unique_together={('seminarist', 'insurance')},
        ),
    ]
