# Generated by Django 4.2.1 on 2023-11-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0009_insuranceplanseminarist_seminaristprofile_and_more'),
        ('usersProfile', '0009_merge_20230825_1315'),
    ]

    operations = [
    ]
