# Generated by Django 4.2.1 on 2023-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0010_merge_20231118_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
