# Generated by Django 4.2.1 on 2024-05-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0013_specialitybranch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='copayment',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterUniqueTogether(
            name='specialitybranch',
            unique_together={('name', 'speciality')},
        ),
    ]
