# Generated by Django 4.2.1 on 2024-05-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0013_specialitybranch_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialitybranch',
            unique_together={('name', 'speciality')},
        ),
    ]
