# Generated by Django 4.2.1 on 2024-05-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0014_alter_specialitybranch_unique_together'),
        ('usersProfile', '0014_doctorprofile_copayment_and_more'),
    ]

    operations = [
    ]
